name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Environment
      run: sudo apt-get update && sudo apt-get install -y <依赖包名称>

    - name: Build
      run: make

    - name: Test
      run: make test
